name: Standard Build

on: 
  pull_request:
    branches: 
      - master
      - develop

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: Prepare For Build
      run: gem install cocoapods && gem install xcpretty
      
    - name: Install Pods
      run: pod install

    - name: Run Build
      run: set -o pipefail && xcodebuild -workspace KnightHacks.xcworkspace -scheme KnightHacks -sdk iphonesimulator -only-testing:KnightHacksTests build -destination "platform=iOS Simulator,name=iPhone 11 Pro" | xcpretty

    - name: Run Tests
      run: set -o pipefail && xcodebuild -workspace KnightHacks.xcworkspace -scheme KnightHacks -sdk iphonesimulator -only-testing:KnightHacksTests test -destination "platform=iOS Simulator,name=iPhone 11 Pro" | xcpretty
